### ISSUE TITLE
Figure out how to type-check api responses

### ISSUE THREAD

**Issue by gianluca-sabena** [unicredit/sbt-swagger-codegen#11]
Swagger spec allow to define multiple responses https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#responses-object

Figure out how to generate a code with type-check of multiple responses.

**Comment by mfirry** [comment]
I think this is already covered (judging from the examples). See https://github.com/unicredit/sbt-swagger-codegen-examples/blob/master/src/main/swagger/petStore.yaml#l47#l57 

@andreaTP, did I get it wrong?

**Comment by gianluca-sabena** [comment]
It is possible to define multiple responses in swagger file, but code generated didn't type-check it.

Codegen produces this controller function

```
  def findPets(limit: Option[Int], tags: Option[List[String]]) = {
    Action.async(request => {
      findPetsImpl(limit, tags).map(answer => Ok(Json.toJson(answer)))
    }.recoverWith({
      case (err: Throwable) => {
        onError("findPets", err).map(errAnswer => BadRequest(errAnswer))
      }
    }))
  }
```

There is no check on type returned from findPetsImpl, this allow to return a type in contrast with swagger.yaml definition

**Comment by mfirry** [comment]
Ok. I thought you were talking about multiple responses in general.
My two cents on this:

One way to do this would be an explicit `val` declaration (**with its type**) every time an implementation method gets called.
In your case this will be:

```
val pets: Seq[Pet] = findPetsImpl(limit, tags)
pets.map(answer => Ok(Json.toJson(answer)))
```

Same for the error case, since you're required to implement `onError` method anyway... so one could do:

```
val e: errorModel = onError("findPets", err)
e.map(errAnswer => BadRequest(errAnswer))
```

It isn't clear to me what they mean by multiple responses. I clearly see cases with a **good** result and an **error** one. But I can't see good examples of exposing more than two cases.

What do you guys think?

**Comment by gianluca-sabena** [comment]
I think it's possible to simplify and reduce to one success case and multiple "non success" cases (eg. 400, 401, 403. 404, 50X )

A possible implementation

``` yaml
# api.yaml
...
    get:
      description: Get token info
      operationId: AuthGet
      parameters:
        - name: xauth
          in : query
          type: string
          required: true
      responses:
        '200':
          description: auth response
          schema:
            $ref: '#/definitions/AuthRes'
        '401':
          description:  Unauthorized, x-auth-header not provided or invalid
          schema:
            $ref: '#/definitions/ErrorModel'
        '403':
          description:  Forbidden - The server understood the request, but is refusing to fulfill it
          schema:
            $ref: '#/definitions/ErrorModel'
        '404':
          description: Not Found The server has not found anything matching the Request-URI
          schema:
            $ref: '#/definitions/ErrorModel'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
```

Code

``` scala

// code generated from swagger sbt plugin

object AuthGetEither extends Controller {
  def authGet(param: String) =
    Action {
      val r: (Int, Either[ErrorModel, AuthRes]) = AuthGetEitherImpl.authGet(param)
      r match {
        case (_,Right(r)) => Ok(Json.toJson(r))
        case (401, Left(e)) => Unauthorized(Json.toJson(e))
        case (403, Left(e)) => Forbidden(Json.toJson(e))
        case (404, Left(e)) => NotFound(Json.toJson(e))
        case (_ , Left(e)) => BadRequest(Json.toJson(e))
      }
    }
}

// code implemented by user

object AuthGetEitherImpl {
  def authGet(param: String): (Int, Either[ErrorModel, AuthRes]) = {
    if (param.length > 0) (200, Right(AuthRes(Some(param))))
    // else if ...
    // ... ErrorModel(40X, Y, "error message")
    else (404, Left(ErrorModel(404,0, "error message")))

  }
}
```

**Comment by andreaTP** [comment]
cannot find a general solution, added a light check of ok responses,
we will be back on this in the future.
