### ISSUE TITLE
Generating deprecated code when used with Play 2.5.x

### ISSUE THREAD

**Issue by harshvs20** [unicredit/sbt-swagger-codegen#14]
I am trying to use plugin with latest Play 2.5.x but unfortunately it is generating deprecated code.

Do you have any suggestion/advice to make this plugin compatible with the latest PlayFramework ?

**Comment by andreaTP** [comment]
It was actually just in the Client side generation.
Thanks for the notify!

**Comment by harshvs20** [comment]
Thanks :)
