### ISSUE TITLE
module not found: eu.unicredit#sbt-swagger-codegen;0.0.4-SNAPSHOT

### ISSUE THREAD

**Issue by wontheone1** [unicredit/sbt-swagger-codegen#15]
just cloned the example project(from https://github.com/unicredit/sbt-swagger-codegen-examples) and tried to build but I got this module not found Resolve Error. My complete log is below.

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
[info] Loading project definition from /Users/wseobseo/zalando/sbt-swagger-codegen-examples/project
[info] Updating {file:/Users/wseobseo/zalando/sbt-swagger-codegen-examples/project/}sbt-swagger-codegen-examples-build...
[info] Resolving eu.unicredit#sbt-swagger-codegen;0.0.4-SNAPSHOT ...
[info] Resolving eu.unicredit#sbt-swagger-codegen;0.0.4-SNAPSHOT ...
[warn]  module not found: eu.unicredit#sbt-swagger-codegen;0.0.4-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/eu.unicredit/sbt-swagger-codegen/scala_2.10/sbt_0.13/0.0.4-SNAPSHOT/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/eu.unicredit/sbt-swagger-codegen/scala_2.10/sbt_0.13/0.0.4-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/wseobseo/.ivy2/local/eu.unicredit/sbt-swagger-codegen/scala_2.10/sbt_0.13/0.0.4-SNAPSHOT/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   /Users/wseobseo/activator/repository/eu.unicredit/sbt-swagger-codegen/scala_2.10/sbt_0.13/0.0.4-SNAPSHOT/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /Users/wseobseo/.activator/repository/eu.unicredit/sbt-swagger-codegen/scala_2.10/sbt_0.13/0.0.4-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/eu/unicredit/sbt-swagger-codegen_2.10_0.13/0.0.4-SNAPSHOT/sbt-swagger-codegen-0.0.4-SNAPSHOT.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/eu/unicredit/sbt-swagger-codegen_2.10_0.13/0.0.4-SNAPSHOT/sbt-swagger-codegen-0.0.4-SNAPSHOT.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/eu.unicredit/sbt-swagger-codegen/scala_2.10/sbt_0.13/0.0.4-SNAPSHOT/ivys/ivy.xml
[info] Resolving com.typesafe.play#sbt-plugin;2.4.0 ...
[info] Resolving com.typesafe.play#routes-compiler_2.10;2.4.0 ...
[info] Resolving org.scala-lang#scala-library;2.10.5 ...
[info] Resolving com.typesafe.play#twirl-api_2.10;1.1.1 ...
[info] Resolving org.apache.commons#commons-lang3;3.4 ...
[info] Resolving commons-io#commons-io;2.4 ...
[info] Resolving com.typesafe.play#sbt-run-support_2.10;2.4.0 ...
[info] Resolving com.typesafe.play#build-link;2.4.0 ...
[info] Resolving com.typesafe.play#play-exceptions;2.4.0 ...
[info] Resolving org.javassist#javassist;3.19.0-GA ...
[info] Resolving com.typesafe#config;1.3.0 ...
[info] Resolving com.google.guava#guava;18.0 ...
[info] Resolving com.h2database#h2;1.4.187 ...
[info] Resolving net.contentobjects.jnotify#jnotify;0.94-play-1 ...
[info] Resolving com.typesafe.sbt#sbt-twirl;1.1.1 ...
[info] Resolving com.typesafe.play#twirl-compiler_2.10;1.1.1 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.5 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.5 ...
[info] Resolving com.typesafe.play#twirl-parser_2.10;1.1.1 ...
[info] Resolving com.typesafe.sbt#sbt-native-packager;1.0.1 ...
[info] Resolving org.apache.commons#commons-compress;1.4.1 ...
[info] Resolving org.tukaani#xz;1.0 ...
[info] Resolving org.vafer#jdeb;1.3 ...
[info] Resolving org.apache.commons#commons-compress;1.7 ...
[info] Resolving org.tukaani#xz;1.4 ...
[info] Resolving org.apache.maven#maven-core;3.2.2 ...
[info] Resolving org.apache.maven#maven-model;3.2.2 ...
[info] Resolving org.codehaus.plexus#plexus-utils;3.0.17 ...
[info] Resolving org.apache.maven#maven-settings;3.2.2 ...
[info] Resolving org.apache.maven#maven-settings-builder;3.2.2 ...
[info] Resolving org.codehaus.plexus#plexus-interpolation;1.19 ...
[info] Resolving org.codehaus.plexus#plexus-component-annotations;1.5.5 ...
[info] Resolving org.sonatype.plexus#plexus-sec-dispatcher;1.3 ...
[info] Resolving org.sonatype.plexus#plexus-cipher;1.4 ...
[info] Resolving org.apache.maven#maven-repository-metadata;3.2.2 ...
[info] Resolving org.apache.maven#maven-artifact;3.2.2 ...
[info] Resolving org.apache.maven#maven-plugin-api;3.2.2 ...
[info] Resolving org.eclipse.sisu#org.eclipse.sisu.plexus;0.0.0.M5 ...
[info] Resolving javax.enterprise#cdi-api;1.0 ...
[info] Resolving javax.annotation#jsr250-api;1.0 ...
[info] Resolving javax.inject#javax.inject;1 ...
[info] Resolving org.sonatype.sisu#sisu-guice;3.1.0 ...
[info] Resolving aopalliance#aopalliance;1.0 ...
[info] Resolving org.eclipse.sisu#org.eclipse.sisu.inject;0.0.0.M5 ...
[info] Resolving org.apache.maven#maven-model-builder;3.2.2 ...
[info] Resolving org.apache.maven#maven-aether-provider;3.2.2 ...
[info] Resolving org.eclipse.aether#aether-api;0.9.0.M2 ...
[info] Resolving org.eclipse.aether#aether-spi;0.9.0.M2 ...
[info] Resolving org.eclipse.aether#aether-util;0.9.0.M2 ...
[info] Resolving org.eclipse.aether#aether-impl;0.9.0.M2 ...
[info] Resolving org.codehaus.plexus#plexus-classworlds;2.5.1 ...
[info] Resolving org.apache.ant#ant;1.9.3 ...
[info] Resolving org.apache.ant#ant-launcher;1.9.3 ...
[info] Resolving org.bouncycastle#bcpg-jdk15on;1.51 ...
[info] Resolving org.bouncycastle#bcprov-jdk15on;1.51 ...
[info] Resolving com.typesafe.sbt#sbt-web;1.2.0 ...
[info] Resolving com.typesafe.akka#akka-actor_2.10;2.3.9 ...
[info] Resolving org.webjars#webjars-locator;0.21 ...
[info] Resolving org.slf4j#slf4j-api;1.7.7 ...
[info] Resolving com.fasterxml.jackson.core#jackson-databind;2.3.3 ...
[info] Resolving com.fasterxml.jackson.core#jackson-annotations;2.3.0 ...
[info] Resolving com.fasterxml.jackson.core#jackson-core;2.3.3 ...
[info] Resolving com.typesafe.sbt#sbt-js-engine;1.1.2 ...
[info] Resolving com.typesafe#jse_2.10;1.1.1 ...
[info] Resolving com.typesafe.akka#akka-contrib_2.10;2.3.9 ...
[info] Resolving com.typesafe.akka#akka-remote_2.10;2.3.9 ...
[info] Resolving io.netty#netty;3.8.0.Final ...
[info] Resolving com.google.protobuf#protobuf-java;2.5.0 ...
[info] Resolving org.uncommons.maths#uncommons-maths;1.2.2a ...
[info] Resolving com.typesafe.akka#akka-cluster_2.10;2.3.9 ...
[info] Resolving com.typesafe.akka#akka-persistence-experimental_2.10;2.3.9 ...
[info] Resolving org.iq80.leveldb#leveldb;0.5 ...
[info] Resolving org.iq80.leveldb#leveldb-api;0.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-all;1.7 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni;1.7 ...
[info] Resolving org.fusesource.hawtjni#hawtjni-runtime;1.8 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-osx;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-linux32;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-linux64;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-win32;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-win64;1.5 ...
[info] Resolving io.apigee.trireme#trireme-core;0.8.5 ...
[info] Resolving io.apigee#rhino;1.7R5pre4 ...
[info] Resolving io.apigee.trireme#trireme-node10src;0.8.5 ...
[info] Resolving io.spray#spray-json_2.10;1.3.2 ...
[info] Resolving org.slf4j#slf4j-simple;1.7.12 ...
[info] Resolving org.slf4j#slf4j-api;1.7.12 ...
[info] Resolving com.typesafe#npm_2.10;1.1.0 ...
[info] Resolving org.webjars#npm;1.3.26 ...
[info] Resolving org.scala-sbt#sbt;0.13.9 ...
[info] Resolving org.scala-sbt#main;0.13.9 ...
[info] Resolving org.scala-sbt#actions;0.13.9 ...
[info] Resolving org.scala-sbt#classpath;0.13.9 ...
[info] Resolving org.scala-sbt#interface;0.13.9 ...
[info] Resolving org.scala-sbt#io;0.13.9 ...
[info] Resolving org.scala-sbt#control;0.13.9 ...
[info] Resolving org.scala-sbt#launcher-interface;1.0.0-M1 ...
[info] Resolving org.scala-sbt#completion;0.13.9 ...
[info] Resolving org.scala-sbt#collections;0.13.9 ...
[info] Resolving jline#jline;2.11 ...
[info] Resolving org.scala-sbt#api;0.13.9 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.9 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.9 ...
[info] Resolving org.scala-sbt#logging;0.13.9 ...
[info] Resolving org.scala-sbt#process;0.13.9 ...
[info] Resolving org.scala-sbt#relation;0.13.9 ...
[info] Resolving org.scala-sbt#compile;0.13.9 ...
[info] Resolving org.scala-sbt#classfile;0.13.9 ...
[info] Resolving org.scala-sbt#persist;0.13.9 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.9 ...
[info] Resolving org.scala-sbt#ivy;0.13.9 ...
[info] Resolving org.scala-sbt#cross;0.13.9 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-c5d1b95fdcc1e1007740ffbecf4eb07abc51ec93 ...
[info] Resolving com.jcraft#jsch;0.1.46 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.1 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.0 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.9 ...
[info] Resolving org.scala-sbt#task-system;0.13.9 ...
[info] Resolving org.scala-sbt#tasks;0.13.9 ...
[info] Resolving org.scala-sbt#tracking;0.13.9 ...
[info] Resolving org.scala-sbt#cache;0.13.9 ...
[info] Resolving org.scala-sbt#testing;0.13.9 ...
[info] Resolving org.scala-sbt#test-agent;0.13.9 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.9 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.9 ...
[info] Resolving org.scala-sbt#command;0.13.9 ...
[info] Resolving org.scala-sbt#logic;0.13.9 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.9 ...
[info] Resolving org.scala-lang#jline;2.10.5 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: eu.unicredit#sbt-swagger-codegen;0.0.4-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      eu.unicredit:sbt-swagger-codegen:0.0.4-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      eu.unicredit:sbt-swagger-codegen:0.0.4-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13) (/Users/wseobseo/zalando/sbt-swagger-codegen-examples/project/plugins.sbt#L1-2)
[warn]        +- default:sbt-swagger-codegen-examples-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: eu.unicredit#sbt-swagger-codegen;0.0.4-SNAPSHOT: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:168)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error](*:update) sbt.ResolveException: unresolved dependency: eu.unicredit#sbt-swagger-codegen;0.0.4-SNAPSHOT: not found
Invalid response.
Invalid response.

**Comment by andreaTP** [comment]
thanks for reporting!
fixed on master!
https://github.com/unicredit/sbt-swagger-codegen-examples/blob/master/project/plugins.sbt#L1

...still we need to update the example and publish a more recent version of the plugin...
