### ISSUE TITLE
sourceGenerators instead of command + task?

### ISSUE THREAD

**Issue by dwunsch** [unicredit/sbt-swagger-codegen#24]
at the moment there are two ways of generating code: a command, and additionally a task.
both write code into src/main. imho generated code should neither go into src/ nor should it be checked into version control.

i propose to replace this with sourceGenerators so code will be generated into target/src_managed whenever a project is compiled.

**Comment by andreaTP** [comment]
Hi @dwunsch ,
I will try to take a look at everything you propose within this week.
We are currently on projects deadline and have few time unfortunately, but please, keep in touch even with me by mail (find it in my github profile) to share ideas! :-)

**Comment by andreaTP** [comment]
ok, please submit a PR for this, should be easy :-)

Thanks for the idea!

**Comment by dwunsch** [comment]
i would, but my other two PRs have been lying around uncommented for a month now, so i'm starting to consider a fork.

**Comment by andreaTP** [comment]
sorry it's a really busy period!

**Comment by dwunsch** [comment]
actually it's not that easy, the generation of play routes and controllers is quite different from client- and model generation:
- auto-generating model and client on compile in src_managed totally makes sense
- routes and controllers, on the other hand, are meant to be generated once, and then checked in and modified by hand.

**Comment by andreaTP** [comment]
Good point about routes, instead generated  controllers are not supposed to be modified, so they can freely go in src_managed

**Comment by dwunsch** [comment]
there might be a way to tell play to merge the generated routes with manually created ones - i'll have a look into that.

if controllers are not to be modified manually - how does one do the actual implementation then?

**Comment by andreaTP** [comment]
With new versions of play you can define routes within code, this will be much better and robust. You are asked to implement an interface like is done in the example, drop me an email if this is not clear!

**Comment by andreaTP** [comment]
This should be fixed now by #29
