### ISSUE TITLE
My thoughts on this project

### ISSUE THREAD

**Issue by eboto** [unicredit/sbt-swagger-codegen#3]
Hey Andrea! Thanks for the merge on #2. To answer your question, yes I am currently using the plugin; I have incorporated it into a 3-service microservice sbt build. My opinions on the project? Beyond that I found it cool enough to start using...
- I think it's a great idea. Something like this is absolutely necessary for building play/scala microservices while maintaining the benefits of type safety.
- I'm struggling with how to generating model definitions that are shared between many API specs. For example I could have a `users` microservice and a `companies` microservice, with corresponding `users.yaml` and `companies.yaml`.  I want both `User` and `Company` to use a custom `URN` as an ID rather than just a Long or a String. However I can't see any way to define a URN in another swagger file (with its own package name) and then use it in my direct API swagger files. This could be because I'm new to swagger.
- I think the codegen has a long way to go before actually matching some of the more obscure corners of the swagger spec. (e.g. models that extend "string" instead of "object")
- I'm afraid that the one file with all the settings and defaults will become huge as number of configuration options proliferate. There's probably something we can do to simplify that when it becomes a problem.
- I'm running into a large number of NPEs even when matching the swagger spec. I haven't been diligent about patching all of them. I'll try to do that moving forward.
- I wonder what will happen when new play versions change their APIs? I wonder how the plugin will support the new syntax.

That exhausts most of my thoughts on the topic =)

As a follow-up, what are your plans for building and maintaining this plugin? What's your use-case?

**Comment by andreaTP** [comment]
Thanks a lot for sharing your thoughts!

Inheritance and "source merging" on Swagger spec are hot topics also for me!
About the first I've found that polymorphism is supported:
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md
in section `Models with Polymorphism Support`
and it is great, in your use case you can define a `URN` definition and then use it in the rest of your yaml.

Unfortunately the second point is not covered at all from the specification, I've implemented a very rough "yaml source merging" just to avoid stupid errors in generated code, but I think that future work on this project will cover this point in some way.

On corner cases, err..., you are right, especially support for primitive swagger types in body and responses is totally uncovered at the moment, I've developed as a consequence of having to struggle with swagger for a project with short deadlines, so, I've started covering all my use cases.
Probably with a little bit of refactoring of the CodeGen file it will become even easier to implement and cover cases as soon as they are needed.

The new play API looks great! As soon as I have time to upgrade I will try to support it.

This plugin as you can see is under the `unicredit` umbrella and so we are going to use it in projects and to support it, this is only a starting point and I have colleagues that are going to use and develop with/on it.
At the moment the biggest use case is mine and is a 8 microservices infrastructure to support pricing evaluations, the plugin is used for generating both SPA Api and intra microservices communication too.
