### ISSUE TITLE
incomplete data type support

### ISSUE THREAD

**Issue by dwunsch** [unicredit/sbt-swagger-codegen#30]
Some data types lead to code containing ```json.asOpt[Any]``` which cannot be compiled.

i see two solutions here:
- complete the set of supported property types
- present unknown types as String instead of as Any

**Comment by andreaTP** [comment]
I understand that the second point is much easier but the first one will be the only way to go to keep it rigth and not misleading.

**Comment by dwunsch** [comment]
i have some code lying around that lets the plugin just throw an exception for unsupported types instead of silently generating code that doesn't compile later - maybe that's worth a pr in itself?

**Comment by fralken** [comment]
That would be good. Then we can add support for other types later.
