### ISSUE TITLE
generate routes as code instead of a routes file

### ISSUE THREAD

**Issue by dwunsch** [unicredit/sbt-swagger-codegen#31]
so hand-written routes won't be overwritten

see https://www.playframework.com/documentation/2.5.x/ScalaSirdRouter

see #24 for more about the motivation behind this

**Comment by andreaTP** [comment]
Yes, this will be the road ahead. Thanks for pointing out.

**Comment by fralken** [comment]
The easiest way to bind a sird router is as described in [Using SIRD router from a routes files](https://www.playframework.com/documentation/2.5.x/ScalaSirdRouter#using-sird-router-from-a-routes-files), but this implies the the developer should manually add a line like this:
`->      /api                        api.ApiRouter`
to their `conf/routes` file. I don't know if this is practical.
I cannot figure out a solution that is fully transparent for the developer.

**Comment by fralken** [comment]
done in 0.0.12-SNAPSHOT
