### ISSUE TITLE
scalafmt fails with NoClassDefFoundError

### ISSUE THREAD

**Issue by dwunsch** [unicredit/sbt-swagger-codegen#35]
trying to compile broken code (brace/parens mismatch) makes scalafmt thow a
```java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class```
before scalac has a chance to tell me what's actually wrong.

**Comment by dwunsch** [comment]
apart from that, scalafmt as it is configured at the moment makes it very hard to read the treehugger dsl

**Comment by fralken** [comment]
I think this is more a scalafmt issue. Maybe this is fixed in version 0.5.0?

scalafmt was @andreaTP 's  choice. I have to play with it more to understand if it is really useful.

Anyway I have to admit that it is not easy to make a treehugger dsl code readable.

**Comment by fralken** [comment]
I updated to sbt-scalafmt 0.5.1. `reformatOnCompileSettings` is no more available, `scalafmt` command must be explicitly invoked for code formatting.
