### ISSUE TITLE
bad client code for multiple routes with the same suffix

### ISSUE THREAD

**Issue by dwunsch** [unicredit/sbt-swagger-codegen#48]
for example /foo/quux and /bar/quux both get compiled to a method named "quux", and if their parameter types match the resultung code does not compile any more

**Comment by fralken** [comment]
The method name is taken from the `operationId` property of the `Operation` object, that must be unique among all operations described in the API. See [Swagger specification](http://swagger.io/specification/#fixed-fields-37) for more details.

**Comment by dwunsch** [comment]
hm, i somehow thought the name was derived from the last part of the path, but here https://github.com/unicredit/sbt-swagger-codegen/blob/master/lib/src/main/scala/eu/unicredit/swagger/generators/DefaultClientGenerator.scala#L59 the code indeed looks good. 

i can't really remember how the swagger file i had this issue with looked, but could it be the swagger parser/model re-uses the path suffix somehow when the operationId is missing in the swagger file?

**Comment by fralken** [comment]
Well actually if the operationId is missing the field is null and the client generator throws an exception (not the server generator, though).
