### ISSUE TITLE
scalafmt makes treehugger code hard to read

### ISSUE THREAD

**Issue by dwunsch** [unicredit/sbt-swagger-codegen#49]
especially the fact that chained method calls get indented like here:
https://github.com/unicredit/sbt-swagger-codegen/blob/master/lib/src/main/scala/eu/unicredit/swagger/generators/DefaultClientGenerator.scala#L191
can this indent feature be switched off?

an alternative would be to use ```// format: off``` for treehugger-code, but that kind of defeats the purpose of an autoformatter as treehugger AST makes up quite a big part of the code this project has.

**Comment by mfirry** [comment]
I'd go for ```// format: off``` for now. What do @andreaTP and @fralken think?

**Comment by fralken** [comment]
Scalafmt now is not automatic during compilation, you must explicitly invoke `scalafmt` to format code.
The idea was to help formatting treehugger AST code, which is intrinsically hard to read, but without imposing it, that it could be quite annoying sometimes.

Do you think it would be better to get rid of it completely?
Scalafmt reason was to help formatting AST code, disabling just for it doen't make much sense to me.

**Comment by fralken** [comment]
Now Scalameta is used for code generation
