### ISSUE TITLE
how to work with dependency injection?

### ISSUE THREAD

**Issue by rethab** [unicredit/sbt-swagger-codegen#54]
Hi,

as play is moving into a direct of becoming more and more stateless, how would I best implement the controller w/o the need to pull in my dependencies via `Play.current`? I thought about writing a custom controller generator, in which I could specify a list of dependencies. However at that point, I could as well just write the controller myself, because I'd need to have a generator pretty much for every controller.

Any thoughts?

- Reto

**Comment by fralken** [comment]
Hi, can you provide an example of what you are trying to achieve?

**Comment by rethab** [comment]
What is currently generated (roughly):
```scala
class MyController extends MyControllerImpl {
  def myAction(x: String) = myActionImpl(x)
}
```

Now if I wanted to implement `MyController` with dependencies, like so:
```scala
class MyControllerImpl @Inject() (myService: Service) {
  def myActionImpl(x: String) = myService.foo(x)
}
```

The problem is that the way `MyController` integrates with the generated controller (via inheritance) makes it impossible to use dependency injection.

**Comment by fralken** [comment]
I see. Indeed you are right.
What if the generated controller is something like

```scala
class MyController @Inject() (m: MyControllerImpl) {
  def myAction(x: String) = m.myAction(x)
}
```

and the implementation is something like

```scala
class MyControllerImpl @Inject() (myService: Service) {
  def myAction(x: String) = myService.foo(x)
}
```

So we would replace inheritance with DI.
What do you think?

**Comment by rethab** [comment]
That would work, yes. However you don't have to change that for me -- I think I'm going to write my own controllers anyway. I'm happy enough with the case class generation and json reads/writes ;)

Thanks anyway!

**Comment by scf37** [comment]
Please publish new plugin version with b576f4cfe0ff84d53935551b6ef3ad97b5d9a823

**Comment by fralken** [comment]
Version 0.0.10 released and published.
