### ISSUE TITLE
play jsonparser: suggestion for safer parsing

### ISSUE THREAD

**Issue by rethab** [unicredit/sbt-swagger-codegen#70]
hi,

I think the parser could be improved a bit to generate safer code. However I'm not sure how feasible such a change actually is..

# Issue
I think the DefaultJsonGenerator unnecessarily generates unsafe play-json parser code, which will throw an exception rather than a normal parser failure if the json cannot be parsed.

# Detailed Description
Suppose I have these yaml files (excerpt):
```yaml
  OfferRequest:
    type: object
    required:
      - offer
    properties:
      offer:
        $ref: '#/definitions/Offer'
```
```yaml
  Offer:
    type: object
    required:
      - id
      - etc..
```

This is the parser code it generates:
```scala
implicit lazy val OfferRequestReads: Reads[OfferRequest] = Reads[OfferRequest] {
    json => JsSuccess(OfferRequest((json \ "offer").as[Offer]))
}
```

So it uses an unsafe method (`.as`) and wraps that in a success value (`JsSuccess`).

`.as` throws an exception if the parsing fails:

JsReadable.scala from play-json
```scala
  def as[T](implicit fjs: Reads[T]): T = validate(fjs).fold(
    valid = identity,
    invalid = e => throw new JsResultException(e)
  )
```

### Problem

The problem with the unsafe version is that this code does not what you think it does:
```scala
request.body.validate[OfferRequest].asEither {
  case Right(offer) =>
  case Left(validationErrors) =>
}
```
If the validation fails, you will not get a `Left` here, but an exception will be thrown.

### Proposal
This code could be rewritten to:
```scala
 implicit lazy val OfferRequestReads: Reads[OfferRequest] = Reads[OfferRequest] {
    json => (json \ "offer").validate[Offer].map(OfferRequest)
  }
```

Now as I said, this might sound easier than done. I'm not sure how feasible it would be to adapt the generator.

**Comment by andreaTP** [comment]
Looks good to me. You will need to change this line accordingly:

https://github.com/unicredit/sbt-swagger-codegen/blob/master/lib/src/main/scala/eu/unicredit/swagger/generators/DefaultJsonGenerator.scala#L67

Here is an opportunity for a PR :-)

Please note that while the update is not published you can already provide your implementation of a `JsonGenerator` within your codebase, an example is available here:
https://github.com/unicredit/sbt-swagger-codegen-examples/blob/extending/build.sbt#L33

**Comment by rethab** [comment]
Thanks Andrea, I'll give it a shot as soon as I have time :)

**Comment by fralken** [comment]
Hello @rethab how would the code of `OfferRequestReads` be if `OfferRequest` had two or more parameters (e.g. `OfferRequest(offer: Offer, id: String ...)`?

EDIT: ok, a for comprehension can do the trick, such as
```scala
implicit lazy val OfferRequestReads: Reads[OfferRequest] = Reads[OfferRequest] {
    json => for {
      offer <- (json \ "offer").validate[Offer]
      id <- (json \ "id").validate[String]
    } yield OfferRequest(offer, id)
}
```

**Comment by rethab** [comment]
hi @fralken, yes that seems to be it.

I see you already fixed this :heart_eyes: thanks so much. please let me know if can help testing :)

**Comment by fralken** [comment]
Yes, you can check out the branch `develop` (see issue #73) and `publishLocal` it (it's version `0.0.12-SNAPSHOT`) so you can test it.
I updated the project `sbt-swagger-codegen-examples`, also in its branch `develop` that you can use as reference for your tests.

**Comment by fralken** [comment]
done in 0.0.12-SNAPSHOT
