### ISSUE TITLE
Plans for swagger-codegen 3.0?

### ISSUE THREAD

**Issue by jmpicnic** [unicredit/sbt-swagger-codegen#72]
A quick question regarding support for OpenAPI 3.0 (swagger-codegen 3.0.8 +). Are you planning to update the sbt plugin? If not, would you be open to guide us to try?

Thanks a lot

Miguel

**Comment by andreaTP** [comment]
I'm not into active development of this plugin, but I'm open to give my experience into updating it, just ping me on a private chat in gitter if you need any help. :-)

**Comment by mfirry** [comment]
Hi @jmpicnic, we currently have no plan for pushing this forward. I'm personally not even sure how much of a change 3.0 is. 
Are you able to reply here and summarize what changes in 3.0? Myself and @fralken might have a look then.

**Comment by mfirry** [comment]
On a second though, looks like swagger-codegen 3.0 changes a lot. @jmpicnic would you like to share you thoughts on this? Do you have any idea of the amount of work this porting might be?

**Comment by fralken** [comment]
We should also think about changing the implementation without using `treehugger`, which is no longer maintained, and maybe switch to `scalameta` instead.

**Comment by mfirry** [comment]
True. I tried, very briefly, to understand how we _could_ drop treehugger and I'm 99% sure it's going to be a huge rewrite from scratch.

**Comment by jmpicnic** [comment]
Thanks a lot for the answers. I think 3.0 is quite an upgrade from 2.0, coming much closer to the Standard JSON-Schema. During these last three weeks I found guardrail: https://github.com/twilio/guardrail that seems to have gone down that path. Although I have not put it yet in production, it seems to be a solid base. It may be interesting to join forces with them.

Unfortunately, I am still finding my way in Scala after many years in Java, and ~5 years in powerpoint land, so I would not dare to try this project on my own. At least not yet :-).

M.

**Comment by mfirry** [comment]
Thanks @jmpicnic. Yes guardrail looks very nice (I think @andreaTP is using it). We'll keep an eye on that and on 3.0 and see. I'll close this but feel free to comment back if you want.
