### ISSUE TITLE
Generate Illegal format in router when define the multiple parameter api.

### ISSUE THREAD

**Issue by RyoNishikawa** [unicredit/sbt-swagger-codegen#77]
I used this plugin 0.1.0-SNAPSHOT.

But, I think that DefaultServerGenerator.scala have one malfunction. When api with multiple parameters is defined, generate illegal format.

For example, if defined the api 'GET /sample/path?a=xxxxx&b=xxxxx&c=xxxxx', generate following code.

```scala
case GET(p"/sample/path" ? q"a=${a}" & (q"b=${b}", q"c=${c}")) => ...
```

I think, it be supported to generate following code.

```scala
case GET(p"/sample/path" ? q"a=${a}" & q"b=${b}" & q"c=${c}") => ...
```

**Comment by fralken** [comment]
Indeed I misunderstood Scalameta documentation...
